---
language: java
before_script:
- if [ "$CLOUD_FOUNDRY_CONFIG_PATH" != "" ]; then psql -c 'create database cloud_controller;'
  -U postgres; fi
- if [ "$CLOUD_FOUNDRY_CONFIG_PATH" != "" ]; then psql -c 'create database uaa;' -U
  postgres; fi
- if [ "$CLOUD_FOUNDRY_CONFIG_PATH" != "" ]; then psql -c 'create role root NOSUPERUSER
  LOGIN INHERIT CREATEDB;' -U postgres; fi
- if [ "$CLOUD_FOUNDRY_CONFIG_PATH" != "" ]; then psql -c "alter role root with password
  'changeme';" -U postgres; fi
before_install:
- git pull --unshallow
install:
- mvn -U clean --quiet -DskipTests=true
- mvn -U install --quiet -DskipTests=true
script:
- "./.run-script.sh"
- mvn test
- kill -9 `cat mvn.pid`
- rm -f mvn.pid
